### ISSUE TITLE
Title en doublon sur plusieurs pages 

### ISSUE THREAD

**Issue by LightInn** [For-Hives/my-makeup#209]
Il y a le Titre de page qui est en doublon sur les urls suivantes  : 

| Title      | URL |
| ----------- | ----------- |
| My Makeup      |  https://my-makeup.fr/ https://my-makeup.fr/politique-de-confidentialite https://my-makeup.fr/auth/signin https://my-makeup.fr/blog https://my-makeup.fr/auth/signup       |
| Pourquoi My Makeup ?   | https://my-makeup.fr/particulier https://my-makeup.fr/maquilleuse        |

**Comment by CinquinAndy** [comment]
done
