### ISSUE TITLE
Init account multiple call vers l'api

### ISSUE THREAD

**Issue by CinquinAndy** [For-Hives/my-makeup#386]
![image](https://github.com/For-Hives/my-makeup/assets/55706543/1f1de47b-321e-4ec6-914f-a5669ed208fd)

toutes les secondes / 2 secondes, on call "me makeup" depuis "init account" ? normal ? Bug ?

**Comment by LightInn** [comment]
hum, cetais supposer etre une feature quand il y avait la validation email ( la page qui sacutalise toute seule quand tu click sur le mail )

**Comment by CinquinAndy** [comment]
ah ! 

je viens de voir dans le code oui

"
function getUserFromSession(session, user, setUser) {
	// call api every 3 seconds
	return setInterval(async () => {
		if (!session) return null

		if (user != null && user.confirmed) return null

		const userData = await fetch(
			`${process.env.NEXT_PUBLIC_API_URL}/api/users/me`,
			{
				method: 'GET',
				headers: {
					// 	token
					'Content-Type': 'application/json',
					Accept: 'application/json',
					Authorization: `Bearer ${session.jwt}`,
				},
			}
		)

		setUser(await userData.json())
	}, 4000)
}"


c'est plus necessaire en vrai non ?

**Comment by CinquinAndy** [comment]
y'a un monde ou je le met en commentaire en vrai ? :d
