### ISSUE TITLE
Front : Page - My Makeup - Politique de confidentialité

### ISSUE THREAD

**Issue by CinquinAndy** [For-Hives/my-makeup#39]
# Front
- [x] Front : Desktop view
- [x] Front : Mobile view

# Fonctionnalities
- [x] Bobby's help

# Quality
- [ ] Lighthouse check
- [ ] IBM Equal Access check

**Comment by WadeFade** [comment]
[Politique_de_confidentialité.docx](https://github.com/CinquinAndy/my-makeup/files/11182999/Politique_de_confidentialite.docx)
