### ISSUE TITLE
Général : password Vault

### ISSUE THREAD

**Issue by CinquinAndy** [For-Hives/my-makeup#56]
# Exploration & mise en place
- [ ] Regarder ce que ça coute en terme de temps & de complexité ce que ça coute de mettre en place un vault de password
- [ ] Essayer de le mettre en place ( conteneurisation etc ) 
- [ ] Déploiement & utilisation de ce dernier

**Comment by WadeFade** [comment]
Solution Open-Source :
https://github.com/hashicorp/vault
https://www.vaultproject.io/
